//Generated by FigmaQML 3.1.1

import QtQuick
import QtQuick.Shapes
Rectangle {
// component (Instance) level: 0 Main Frame
    id: figma_1_35
    // # "Main Frame"
    x:0
    y:0
    width:938
    height:482
    color:"#ff272626"
    clip: true
    Rectangle {
    // component (Instance) level: 0 Upper bar
        id: figma_1_36
        // # "Upper bar"
        x:0
        y:0
        width:938
        height:19
        color:"#ffffffff"
        clip: true
        Rectangle {
        // component (Instance) level: 0 Frame 2
            id: figma_1_37
            // # "Frame 2"
            x:0
            y:0
            width:938
            height:485
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Port Automation
                id: figma_1_38
                // # "Port Automation"
                x:7
                y:0
                width:110
                height:19
                color:"#ff000000"
                text:"Port Automation"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 14
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Rectangle {
            // component (Instance) level: 0 Close Stuff
                id: figma_1_39
                // # "Close Stuff"
                x:890
                y:2
                width:41
                height:14
                color: "transparent"
                clip: true
                Shape {
                // component (Instance) level: 0 Line 1
                    id: figma_1_40
                    // # "Line 1"
                    x:39
                    y:9
                    width:9
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        fillColor: "#ff000000"
                        strokeWidth:0.5
                        strokeColor: "transparent"
                        // component (shapeFill) level: 0
                        id: svgpath_figma_1_40
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            id: path_0_figma_1_40
                            path: "M0 0L9 0L9 -0.5L0 -0.5L0 0Z"
                        }
                    }
                property alias path: path_0_figma_1_40.path
                }
                Shape {
                // component (Instance) level: 0 Line 2
                    id: figma_1_41
                    // # "Line 2"
                    x:39
                    y:3
                    width:9
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        fillColor: "#ff000000"
                        strokeWidth:0.5
                        strokeColor: "transparent"
                        // component (shapeFill) level: 0
                        id: svgpath_figma_1_41
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            id: path_0_figma_1_41
                            path: "M0 0L9 0L9 -0.5L0 -0.5L0 0Z"
                        }
                    }
                property alias path: path_0_figma_1_41.path
                }
                Shape {
                // component (Instance) level: 0 Rectangle 1
                    id: figma_1_42
                    // # "Rectangle 1"
                    x:21
                    y:3
                    width:7
                    height:6
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ff000000"
                        strokeWidth:0.2
                        fillColor:"#ffd9d9d9"
                        // component (shapeFill) level: 0
                        id: svgpath_figma_1_42
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            id: path_0_figma_1_42
                            path: "M0 0L7 0L7 6L0 6L0 0Z"
                        }
                    }
                property alias path: path_0_figma_1_42.path
                }
                Shape {
                // component (Instance) level: 0 Rectangle 2
                    id: figma_1_43
                    // # "Rectangle 2"
                    x:19
                    y:5
                    width:7
                    height:6
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ff000000"
                        strokeWidth:0.2
                        fillColor:"#ffd9d9d9"
                        // component (shapeFill) level: 0
                        id: svgpath_figma_1_43
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            id: path_0_figma_1_43
                            path: "M0 0L7 0L7 6L0 6L0 0Z"
                        }
                    }
                property alias path: path_0_figma_1_43.path
                }
                Shape {
                // component (Instance) level: 0 Line 3
                    id: figma_1_44
                    // # "Line 3"
                    x:6
                    y:7
                    width:8
                    height:0
                    ShapePath {
                        joinStyle: ShapePath.MiterJoin
                        strokeColor: "#ff000000"
                        strokeWidth:0.5
                        fillColor:"transparent"
                        // component (shapeFill) level: 0
                        id: svgpath_figma_1_44
                        fillRule: ShapePath.WindingFill
                        PathSvg {
                            id: path_0_figma_1_44
                            path: "M0 0.25L8 0.25L8 -0.25L0 -0.25L0 0.25Z"
                        }
                    }
                property alias path: path_0_figma_1_44.path
                }
            }
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_45
        // # "Load Db Button"
        x:5
        y:42
        width:85
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Load Database
            id: figma_1_46
            // # "Load Database"
            x:3
            y:7
            width:83
            height:16
            color:"#ffffffff"
            text:"Load Database
"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_47
        // # "Load Db Button"
        x:288
        y:41
        width:67
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Containers
            id: figma_1_48
            // # "Containers"
            x:3
            y:7
            width:61
            height:16
            color:"#ffffffff"
            text:"Containers"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_49
        // # "Load Db Button"
        x:361
        y:41
        width:53
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Vehicles
            id: figma_1_50
            // # "Vehicles"
            x:3
            y:7
            width:47
            height:16
            color:"#ffffffff"
            text:"Vehicles"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_51
        // # "Load Db Button"
        x:420
        y:41
        width:53
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Process
            id: figma_1_52
            // # "Process"
            x:3
            y:7
            width:47
            height:16
            color:"#ffffffff"
            text:"Process"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_53
        // # "Load Db Button"
        x:479
        y:41
        width:57
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 About Us
            id: figma_1_54
            // # "About Us"
            x:3
            y:7
            width:51
            height:16
            color:"#ffffffff"
            text:"About Us"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_56
        // # "Load Db Button"
        x:542
        y:41
        width:28
        height:31
        color:"#ff141313"
        radius:8
        clip: true
        Text {
        // component (Instance) level: 0 Quit
            id: figma_1_57
            // # "Quit"
            x:3
            y:7
            width:22
            height:16
            color:"#ffffffff"
            text:"Quit"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_58
        // # "Load Db Button"
        x:212
        y:42
        width:70
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Port Layout
            id: figma_1_59
            // # "Port Layout"
            x:3
            y:7
            width:64
            height:16
            color:"#ffffffff"
            text:"Port Layout
"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_60
        // # "Load Db Button"
        x:140
        y:42
        width:66
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Open Ports
            id: figma_1_61
            // # "Open Ports"
            x:3
            y:7
            width:65
            height:16
            color:"#ffffffff"
            text:"Open Ports"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 Load Db Button
        id: figma_1_62
        // # "Load Db Button"
        x:96
        y:42
        width:38
        height:31
        color:"#ff141313"
        radius:11
        clip: true
        Text {
        // component (Instance) level: 0 Close
            id: figma_1_63
            // # "Close"
            x:3
            y:6
            width:32
            height:16
            color:"#ffffffff"
            text:"Close"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 11
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Rectangle {
    // component (Instance) level: 0 ui menus
        id: figma_1_65
        // # "ui menus"
        x:0
        y:19
        width:938
        height:18
        color: "transparent"
        clip: true
        Rectangle {
        // component (Instance) level: 0 File Option
            id: figma_1_66
            // # "File Option"
            x:2
            y:0
            width:25
            height:15
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 File
                id: figma_1_67
                // # "File"
                x:3
                y:0
                width:22
                height:16
                color:"#ffffffff"
                text:"File"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
        // component (Instance) level: 0 Option opt
            id: figma_1_68
            // # "Option opt"
            x:38
            y:1
            width:42
            height:15
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Options
                id: figma_1_69
                // # "Options"
                x:0
                y:-1
                width:42
                height:16
                color:"#ffffffff"
                text:"Options"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
        // component (Instance) level: 0 Window opt
            id: figma_1_70
            // # "Window opt"
            x:144
            y:0
            width:45
            height:18
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Window
                id: figma_1_71
                // # "Window"
                x:1
                y:0
                width:42
                height:14
                color:"#ffffffff"
                text:"Window"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
        // component (Instance) level: 0 Process opt
            id: figma_1_72
            // # "Process opt"
            x:91
            y:0
            width:43
            height:16
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Process
                id: figma_1_73
                // # "Process"
                x:0
                y:0
                width:43
                height:16
                color:"#ffffffff"
                text:"Process"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
        // component (Instance) level: 0 Help opt
            id: figma_1_74
            // # "Help opt"
            x:196
            y:0
            width:32
            height:19
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Help
                id: figma_1_75
                // # "Help"
                x:2
                y:1
                width:25
                height:18
                color:"#ffffffff"
                text:"Help"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
        // component (Instance) level: 0 DOcument Opt
            id: figma_1_76
            // # "DOcument Opt"
            x:234
            y:0
            width:57
            height:19
            color: "transparent"
            clip: true
            Text {
            // component (Instance) level: 0 Document
                id: figma_1_77
                // # "Document"
                x:0
                y:2
                width:55
                height:16
                color:"#ffffffff"
                text:"Document"
                font.family: "Tahoma"
                font.italic: false
                font.pixelSize: 11
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
    }
    Rectangle {
    // component (Instance) level: 0 Frame 1
        id: figma_1_79
        // # "Frame 1"
        x:241
        y:79
        width:516
        height:57
        color: "transparent"
        clip: true
        Text {
        // component (Instance) level: 0 Static and Dynamic Scheduling of Automated Guided Vehicles in Port
            id: figma_1_80
            // # "Static and Dynamic Scheduling of Automated Guided Vehicles in Port"
            x:6
            y:8
            width:490
            height:24
            color:"#ffffffff"
            text:"Static and Dynamic Scheduling of Automated Guided Vehicles in Port"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 16
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
        Text {
        // component (Instance) level: 0 Version 1.0.15 Winter 2015
            id: figma_1_81
            // # "Version 1.0.15 Winter 2015"
            x:164
            y:37
            width:173
            height:20
            color:"#ffffffff"
            text:"Version 1.0.15 Winter 2015"
            font.family: "Tahoma"
            font.italic: false
            font.pixelSize: 14
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignLeft
            verticalAlignment: Text.AlignTop
        }
    }
    Text {
    // component (Instance) level: 0 Designed and Impelented by: H. Rashidi (Allameh Tabataba’i University) E. Tsang (University of Essex)
        id: figma_1_82
        // # "Designed and Impelented by: H. Rashidi (Allameh Tabataba’i University) E. Tsang (University of Essex)"
        x:47
        y:224
        width:876
        height:111
        color:"#ffffffff"
        text:"Designed and Impelented by:
 H. Rashidi (Allameh Tabataba’i University)
E. Tsang (University of Essex)"
        font.family: "Tahoma"
        font.italic: false
        font.pixelSize: 16
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignTop
    }
}
